# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Zfit.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1048, 789)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Web Pages/WebPlus/FavIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mpl = MplWidget(self.centralwidget)
        self.mpl.setGeometry(QtCore.QRect(50, 140, 821, 511))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl.sizePolicy().hasHeightForWidth())
        self.mpl.setSizePolicy(sizePolicy)
        self.mpl.setObjectName("mpl")
        self.lineEditData = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditData.setGeometry(QtCore.QRect(100, 20, 431, 20))
        self.lineEditData.setReadOnly(True)
        self.lineEditData.setObjectName("lineEditData")
        self.lineEditModel = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditModel.setGeometry(QtCore.QRect(100, 60, 181, 20))
        self.lineEditModel.setReadOnly(True)
        self.lineEditModel.setObjectName("lineEditModel")
        self.groupBoxDrawing = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxDrawing.setGeometry(QtCore.QRect(550, 0, 231, 91))
        self.groupBoxDrawing.setObjectName("groupBoxDrawing")
        self.layoutWidget = QtWidgets.QWidget(self.groupBoxDrawing)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 83, 65))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButtonWeight = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButtonWeight.setChecked(True)
        self.radioButtonWeight.setObjectName("radioButtonWeight")
        self.gridLayout.addWidget(self.radioButtonWeight, 0, 0, 1, 1)
        self.radioButtonMag = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButtonMag.setObjectName("radioButtonMag")
        self.gridLayout.addWidget(self.radioButtonMag, 1, 0, 1, 1)
        self.radioButtonPha = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButtonPha.setObjectName("radioButtonPha")
        self.gridLayout.addWidget(self.radioButtonPha, 2, 0, 1, 1)
        self.pushButtonDraw = QtWidgets.QPushButton(self.groupBoxDrawing)
        self.pushButtonDraw.setGeometry(QtCore.QRect(110, 20, 111, 31))
        self.pushButtonDraw.setObjectName("pushButtonDraw")
        self.pushButtonClear = QtWidgets.QPushButton(self.groupBoxDrawing)
        self.pushButtonClear.setGeometry(QtCore.QRect(110, 50, 111, 31))
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.pushButtonModel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonModel.setGeometry(QtCore.QRect(900, 100, 101, 31))
        self.pushButtonModel.setObjectName("pushButtonModel")
        self.groupBoxParams = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxParams.setGeometry(QtCore.QRect(880, 140, 151, 581))
        self.groupBoxParams.setObjectName("groupBoxParams")
        self.labelParams = QtWidgets.QLabel(self.groupBoxParams)
        self.labelParams.setGeometry(QtCore.QRect(10, 20, 131, 481))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelParams.setFont(font)
        self.labelParams.setTextFormat(QtCore.Qt.RichText)
        self.labelParams.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelParams.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.labelParams.setObjectName("labelParams")
        self.checkBoxLogMag = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxLogMag.setGeometry(QtCore.QRect(20, 360, 21, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxLogMag.sizePolicy().hasHeightForWidth())
        self.checkBoxLogMag.setSizePolicy(sizePolicy)
        self.checkBoxLogMag.setBaseSize(QtCore.QSize(0, 0))
        self.checkBoxLogMag.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxLogMag.setText("")
        self.checkBoxLogMag.setIconSize(QtCore.QSize(16, 16))
        self.checkBoxLogMag.setObjectName("checkBoxLogMag")
        self.label_LogMag = QtWidgets.QLabel(self.centralwidget)
        self.label_LogMag.setGeometry(QtCore.QRect(10, 380, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_LogMag.setFont(font)
        self.label_LogMag.setAlignment(QtCore.Qt.AlignCenter)
        self.label_LogMag.setObjectName("label_LogMag")
        self.label_LogX = QtWidgets.QLabel(self.centralwidget)
        self.label_LogX.setGeometry(QtCore.QRect(790, 650, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_LogX.setFont(font)
        self.label_LogX.setAlignment(QtCore.Qt.AlignCenter)
        self.label_LogX.setObjectName("label_LogX")
        self.checkBoxLogFreq = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxLogFreq.setGeometry(QtCore.QRect(830, 650, 21, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxLogFreq.sizePolicy().hasHeightForWidth())
        self.checkBoxLogFreq.setSizePolicy(sizePolicy)
        self.checkBoxLogFreq.setBaseSize(QtCore.QSize(0, 0))
        self.checkBoxLogFreq.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxLogFreq.setText("")
        self.checkBoxLogFreq.setIconSize(QtCore.QSize(16, 16))
        self.checkBoxLogFreq.setObjectName("checkBoxLogFreq")
        self.pushButtonHelp = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonHelp.setGeometry(QtCore.QRect(920, 10, 81, 31))
        self.pushButtonHelp.setObjectName("pushButtonHelp")
        self.checkBoxLocked = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxLocked.setGeometry(QtCore.QRect(920, 730, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.checkBoxLocked.setFont(font)
        self.checkBoxLocked.setObjectName("checkBoxLocked")
        self.pushButtonEdit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonEdit.setGeometry(QtCore.QRect(300, 60, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButtonEdit.setFont(font)
        self.pushButtonEdit.setObjectName("pushButtonEdit")
        self.lineEditSegment = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSegment.setGeometry(QtCore.QRect(100, 100, 681, 21))
        self.lineEditSegment.setReadOnly(True)
        self.lineEditSegment.setObjectName("lineEditSegment")
        self.pushButtonNext = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonNext.setEnabled(False)
        self.pushButtonNext.setGeometry(QtCore.QRect(800, 100, 51, 23))
        self.pushButtonNext.setObjectName("pushButtonNext")
        self.comboBoxMethod = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxMethod.setGeometry(QtCore.QRect(800, 60, 181, 22))
        self.comboBoxMethod.setObjectName("comboBoxMethod")
        self.label_Method = QtWidgets.QLabel(self.centralwidget)
        self.label_Method.setGeometry(QtCore.QRect(800, 30, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_Method.setFont(font)
        self.label_Method.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Method.setObjectName("label_Method")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(50, 740, 631, 16))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.groupBoxStatus = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxStatus.setGeometry(QtCore.QRect(50, 660, 631, 71))
        self.groupBoxStatus.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBoxStatus.setObjectName("groupBoxStatus")
        self.labelStatus = QtWidgets.QLabel(self.groupBoxStatus)
        self.labelStatus.setGeometry(QtCore.QRect(10, 20, 471, 41))
        self.labelStatus.setTextFormat(QtCore.Qt.RichText)
        self.labelStatus.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelStatus.setObjectName("labelStatus")
        self.label_Segment = QtWidgets.QLabel(self.centralwidget)
        self.label_Segment.setEnabled(False)
        self.label_Segment.setGeometry(QtCore.QRect(20, 100, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_Segment.setFont(font)
        self.label_Segment.setStyleSheet("")
        self.label_Segment.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Segment.setObjectName("label_Segment")
        self.groupBoxNormDenorm = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxNormDenorm.setGeometry(QtCore.QRect(400, 50, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.groupBoxNormDenorm.setFont(font)
        self.groupBoxNormDenorm.setObjectName("groupBoxNormDenorm")
        self.radioButtonNormDenormOn = QtWidgets.QRadioButton(self.groupBoxNormDenorm)
        self.radioButtonNormDenormOn.setGeometry(QtCore.QRect(10, 20, 41, 17))
        self.radioButtonNormDenormOn.setChecked(True)
        self.radioButtonNormDenormOn.setObjectName("radioButtonNormDenormOn")
        self.radioButtonNormDenormOff = QtWidgets.QRadioButton(self.groupBoxNormDenorm)
        self.radioButtonNormDenormOff.setGeometry(QtCore.QRect(50, 20, 41, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.radioButtonNormDenormOff.setFont(font)
        self.radioButtonNormDenormOff.setObjectName("radioButtonNormDenormOff")
        self.pushButtonDataFile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDataFile.setGeometry(QtCore.QRect(10, 20, 81, 21))
        self.pushButtonDataFile.setObjectName("pushButtonDataFile")
        self.pushButtonModelScript = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonModelScript.setGeometry(QtCore.QRect(10, 60, 81, 23))
        self.pushButtonModelScript.setObjectName("pushButtonModelScript")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1048, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionSave_Plots = QtWidgets.QAction(MainWindow)
        self.actionSave_Plots.setObjectName("actionSave_Plots")
        self.menuFile.addAction(self.actionSave_Plots)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.comboBoxMethod.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Zfit"))
        self.groupBoxDrawing.setTitle(_translate("MainWindow", "Drawing"))
        self.radioButtonWeight.setText(_translate("MainWindow", "&Weight"))
        self.radioButtonWeight.setShortcut(_translate("MainWindow", "W"))
        self.radioButtonMag.setText(_translate("MainWindow", "Ma&gnitude"))
        self.radioButtonMag.setShortcut(_translate("MainWindow", "G"))
        self.radioButtonPha.setText(_translate("MainWindow", "&Phase"))
        self.radioButtonPha.setShortcut(_translate("MainWindow", "P"))
        self.pushButtonDraw.setText(_translate("MainWindow", "&Draw xxx"))
        self.pushButtonDraw.setShortcut(_translate("MainWindow", "D"))
        self.pushButtonClear.setText(_translate("MainWindow", "&Clear xxx"))
        self.pushButtonClear.setShortcut(_translate("MainWindow", "C"))
        self.pushButtonModel.setText(_translate("MainWindow", "&Model"))
        self.pushButtonModel.setShortcut(_translate("MainWindow", "M"))
        self.groupBoxParams.setTitle(_translate("MainWindow", "Parameters"))
        self.labelParams.setText(_translate("MainWindow", "TextLabel"))
        self.label_LogMag.setText(_translate("MainWindow", "Log"))
        self.label_LogX.setText(_translate("MainWindow", "Log"))
        self.pushButtonHelp.setText(_translate("MainWindow", "&Help"))
        self.pushButtonHelp.setShortcut(_translate("MainWindow", "H"))
        self.checkBoxLocked.setText(_translate("MainWindow", "Locked"))
        self.pushButtonEdit.setText(_translate("MainWindow", "Edit"))
        self.pushButtonNext.setText(_translate("MainWindow", "Next"))
        self.label_Method.setText(_translate("MainWindow", "Fitting Method"))
        self.groupBoxStatus.setTitle(_translate("MainWindow", "Status"))
        self.labelStatus.setText(_translate("MainWindow", "TextLabel"))
        self.label_Segment.setText(_translate("MainWindow", "Segment"))
        self.groupBoxNormDenorm.setTitle(_translate("MainWindow", "Norm/Denorm"))
        self.radioButtonNormDenormOn.setText(_translate("MainWindow", "On"))
        self.radioButtonNormDenormOff.setText(_translate("MainWindow", "Off"))
        self.pushButtonDataFile.setText(_translate("MainWindow", "Data File"))
        self.pushButtonModelScript.setText(_translate("MainWindow", "Model Script"))
        self.menuFile.setTitle(_translate("MainWindow", "Plots"))
        self.actionSave_Plots.setText(_translate("MainWindow", "Save..."))

from mplwidget import MplWidget
